#Configuration file.
#Key-Value type of file
#Key:value

server.port=7070

#FakeStore congif variables.
fakestore.api.url = https://fakestoreapi.com
fakestore.api.paths.products = /products
fakestore.api.paths.categories = /categories
